import {
  appendAgentAction,
  appendAgentBrief,
  getOpenBacklogItems,
  listEngineeringTasks,
  listBacklogItems,
  readAgentState,
  updateEngineeringTaskById,
  writeAgentState,
  writeBacklog,
} from "@/lib/agents/store";
import { prepareExecutionPlan } from "@/lib/agents/execution/engine";
import { approveExecution } from "@/lib/agents/governance/manager";
import { nowIso } from "@/lib/agents/time";
import type { AgentBrief, AgentRunnerResult, BacklogItem } from "@/lib/agents/types";

// Context is reserved for future expansion (telemetry, policy signals, etc.).
export async function runEngineeringManagerAgent(_context?: unknown): Promise<AgentRunnerResult> {
  const now = nowIso();
  const currentState = await readAgentState();
  const backlog = await getOpenBacklogItems(200);
  const existingTitles = new Set(backlog.map((item) => item.title.trim().toUpperCase()));

  const tasksToEnsure: Array<{
    title: string;
    summary: string;
    priority: "HIGH" | "MEDIUM";
  }> = [
    {
      title: "Enable GitHub API write access",
      summary: "Allow agents to create branches, commits, and PRs via GitHub API.",
      priority: "HIGH",
    },
    {
      title: "Implement patch executor",
      summary: "Allow system to safely apply code patches generated by agents.",
      priority: "HIGH",
    },
    {
      title: "Add safe commit + deploy pipeline",
      summary: "Create controlled commit, build, and deploy flow with guardrails.",
      priority: "HIGH",
    },
    {
      title: "Add rollback capability",
      summary: "Allow automatic rollback if deploy validation fails.",
      priority: "MEDIUM",
    },
    {
      title: "Add canary deploy validation",
      summary: "Validate new deployments before full rollout.",
      priority: "MEDIUM",
    },
  ];

  const newItems: BacklogItem[] = [];

  for (const task of tasksToEnsure) {
    if (!existingTitles.has(task.title.trim().toUpperCase())) {
      newItems.push({
        id: crypto.randomUUID(),
        createdAt: now,
        updatedAt: now,
        status: "OPEN",
        type: "FEATURE",
        priority: task.priority,
        title: task.title,
        summary: task.summary,
        assignedAgent: "engineering-manager",
      });
    }
  }

  if (newItems.length > 0) {
    // Preserve current open backlog ordering and append newly ensured items.
    await writeBacklog([...backlog, ...newItems]);
  }

  const engineeringTasks = await listEngineeringTasks(200);
  let newlyReadyCount = 0;
  let newlyBlockedCount = 0;
  let latestExecutionReadyTitle: string | null = null;
  let latestExecutionStatus: "READY_FOR_EXECUTION" | "READY_FOR_PUSH" | "BLOCKED" | null = null;

  for (const task of engineeringTasks) {
    if (task.status !== "OPEN" && task.status !== "IN_PROGRESS") continue;

    const approval = approveExecution(task);
    if (!approval.ok) {
      if (task.executionStatus !== "BLOCKED" || task.executionError !== approval.reason) {
        await updateEngineeringTaskById(task.id, {
          status: "BLOCKED",
          executionStatus: "BLOCKED",
          executionError: approval.reason,
          notes: [...(task.notes ?? []), `Execution blocked: ${approval.reason}`].slice(-20),
        });
      }
      newlyBlockedCount += 1;
      if (!latestExecutionStatus) {
        latestExecutionStatus = "BLOCKED";
        latestExecutionReadyTitle = task.title;
      }
      continue;
    }

    const prepared = prepareExecutionPlan(task);
    const needsUpdate =
      task.executionStatus !== prepared.executionStatus ||
      task.executionError != null ||
      !task.patchPlan ||
      !task.validationPlan ||
      !task.commitPlan;

    if (needsUpdate) {
      await updateEngineeringTaskById(task.id, {
        status: prepared.nextTaskStatus,
        patchPlan: prepared.patchPlan,
        validationPlan: prepared.validationPlan,
        commitPlan: prepared.commitPlan,
        executionStatus: prepared.executionStatus,
        executionError: null,
        notes: [...(task.notes ?? []), `Execution readiness prepared: ${prepared.nextTaskStatus}`].slice(-20),
      });
    }

    newlyReadyCount += 1;
    if (!latestExecutionStatus) {
      latestExecutionStatus = prepared.nextTaskStatus;
      latestExecutionReadyTitle = task.title;
    }
  }

  const refreshedBacklog = await listBacklogItems(200);
  const openBacklogCount = refreshedBacklog.filter((item) => item.status === "OPEN" || item.status === "READY").length;
  const inProgressBacklogCount = refreshedBacklog.filter((item) => item.status === "IN_PROGRESS").length;
  const nextBacklogTitles = refreshedBacklog
    .filter((item) => item.status === "OPEN" || item.status === "READY")
    .slice(0, 3)
    .map((item) => item.title);

  const brief: AgentBrief = {
    id: crypto.randomUUID(),
    agent: "engineering-manager",
    briefType: "STATUS",
    createdAt: now,
    title: newItems.length > 0 ? "Engineering manager seeded backlog" : "Engineering manager backlog unchanged",
    summary:
      newItems.length > 0
        ? `Ensured ${tasksToEnsure.length} strategic backlog items and created ${newItems.length} missing item${newItems.length === 1 ? "" : "s"}.`
        : `Strategic backlog already satisfied across ${tasksToEnsure.length} managed items.`,
    details: {
      created: newItems.length,
      ensured: tasksToEnsure.length,
      openExecutionReadyCount: newlyReadyCount,
      blockedTaskCount: newlyBlockedCount,
      latestExecutionTaskTitle: latestExecutionReadyTitle,
      latestExecutionStatus,
      openBacklogCount,
      inProgressBacklogCount,
      nextBacklogTitles,
    },
  };

  await appendAgentBrief(brief);

  const savedState = await writeAgentState({
    ...currentState,
    asOf: now,
    latestBriefId: brief.id,
    openExecutionReadyCount: newlyReadyCount,
    blockedTaskCount: newlyBlockedCount,
    openBacklogCount,
    inProgressBacklogCount,
    nextBacklogTitles,
    latestExecutionTaskTitle: latestExecutionReadyTitle,
    latestExecutionStatus,
    updatedBy: "engineering-manager",
  });

  const action = await appendAgentAction({
    id: crypto.randomUUID(),
    createdAt: now,
    agent: "engineering-manager",
    actionType: "BACKLOG_ENSURE",
    status: "APPLIED",
    summary:
      newItems.length > 0
        ? `Created ${newItems.length} missing strategic backlog item${newItems.length === 1 ? "" : "s"}.`
        : "All strategic backlog items already existed.",
    metadata: {
      created: newItems.length,
      ensured: tasksToEnsure.length,
      executionReadyCount: newlyReadyCount,
      blockedTaskCount: newlyBlockedCount,
      latestExecutionTaskTitle: latestExecutionReadyTitle,
      latestExecutionStatus,
      titles: tasksToEnsure.map((task) => task.title),
    },
  });

  return {
    agent: "engineering-manager",
    state: savedState,
    briefId: brief.id,
    actionId: action.id,
    summary: brief.summary,
  };
}
