import {
  appendAgentAction,
  appendAgentBrief,
  getOpenBacklogItems,
  listBacklogItems,
  readAgentState,
  writeAgentState,
  writeBacklog,
} from "@/lib/agents/store";
import { nowIso } from "@/lib/agents/time";
import type { AgentBrief, AgentRunnerResult, BacklogItem } from "@/lib/agents/types";

// Context is reserved for future expansion (telemetry, policy signals, etc.).
export async function runEngineeringManagerAgent(_context?: unknown): Promise<AgentRunnerResult> {
  const now = nowIso();
  const currentState = await readAgentState();
  const backlog = await getOpenBacklogItems(200);
  const existingTitles = new Set(backlog.map((item) => item.title.trim().toUpperCase()));

  const tasksToEnsure: Array<{
    title: string;
    summary: string;
    priority: "HIGH" | "MEDIUM";
  }> = [
    {
      title: "Enable GitHub API write access",
      summary: "Allow agents to create branches, commits, and PRs via GitHub API.",
      priority: "HIGH",
    },
    {
      title: "Implement patch executor",
      summary: "Allow system to safely apply code patches generated by agents.",
      priority: "HIGH",
    },
    {
      title: "Add safe commit + deploy pipeline",
      summary: "Create controlled commit, build, and deploy flow with guardrails.",
      priority: "HIGH",
    },
    {
      title: "Add rollback capability",
      summary: "Allow automatic rollback if deploy validation fails.",
      priority: "MEDIUM",
    },
    {
      title: "Add canary deploy validation",
      summary: "Validate new deployments before full rollout.",
      priority: "MEDIUM",
    },
  ];

  const newItems: BacklogItem[] = [];

  for (const task of tasksToEnsure) {
    if (!existingTitles.has(task.title.trim().toUpperCase())) {
      newItems.push({
        id: crypto.randomUUID(),
        createdAt: now,
        updatedAt: now,
        status: "OPEN",
        type: "FEATURE",
        priority: task.priority,
        title: task.title,
        summary: task.summary,
        assignedAgent: "engineering-manager",
      });
    }
  }

  if (newItems.length > 0) {
    // Preserve current open backlog ordering and append newly ensured items.
    await writeBacklog([...backlog, ...newItems]);
  }

  const refreshedBacklog = await listBacklogItems(200);
  const openBacklogCount = refreshedBacklog.filter((item) => item.status === "OPEN" || item.status === "READY").length;
  const inProgressBacklogCount = refreshedBacklog.filter((item) => item.status === "IN_PROGRESS").length;
  const nextBacklogTitles = refreshedBacklog
    .filter((item) => item.status === "OPEN" || item.status === "READY")
    .slice(0, 3)
    .map((item) => item.title);

  const brief: AgentBrief = {
    id: crypto.randomUUID(),
    agent: "engineering-manager",
    briefType: "STATUS",
    createdAt: now,
    title: newItems.length > 0 ? "Engineering manager seeded backlog" : "Engineering manager backlog unchanged",
    summary:
      newItems.length > 0
        ? `Ensured ${tasksToEnsure.length} strategic backlog items and created ${newItems.length} missing item${newItems.length === 1 ? "" : "s"}.`
        : `Strategic backlog already satisfied across ${tasksToEnsure.length} managed items.`,
    details: {
      created: newItems.length,
      ensured: tasksToEnsure.length,
      openBacklogCount,
      inProgressBacklogCount,
      nextBacklogTitles,
    },
  };

  await appendAgentBrief(brief);

  const savedState = await writeAgentState({
    ...currentState,
    asOf: now,
    latestBriefId: brief.id,
    openBacklogCount,
    inProgressBacklogCount,
    nextBacklogTitles,
    updatedBy: "engineering-manager",
  });

  const action = await appendAgentAction({
    id: crypto.randomUUID(),
    createdAt: now,
    agent: "engineering-manager",
    actionType: "BACKLOG_ENSURE",
    status: "APPLIED",
    summary:
      newItems.length > 0
        ? `Created ${newItems.length} missing strategic backlog item${newItems.length === 1 ? "" : "s"}.`
        : "All strategic backlog items already existed.",
    metadata: {
      created: newItems.length,
      ensured: tasksToEnsure.length,
      titles: tasksToEnsure.map((task) => task.title),
    },
  });

  return {
    agent: "engineering-manager",
    state: savedState,
    briefId: brief.id,
    actionId: action.id,
    summary: brief.summary,
  };
}
